# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 16:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('Family_Id_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Address', models.CharField(blank=True, default=' ', max_length=100)),
                ('Area', models.CharField(blank=True, default=' ', max_length=100)),
                ('City', models.CharField(blank=True, default=' ', max_length=100)),
                ('Pincode', models.IntegerField(blank=True, default=0)),
                ('State', models.CharField(blank=True, default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Operation_Description', models.TextField()),
                ('Operation_Cost', models.IntegerField()),
                ('Day_of_Operation', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('Title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Master', 'Master')], max_length=6)),
                ('Family_Id_Display', models.IntegerField(blank=True, null=True)),
                ('Patient_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(blank=True, max_length=100)),
                ('Middle_Name', models.CharField(blank=True, max_length=100)),
                ('Last_Name', models.CharField(blank=True, max_length=100)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Area', models.CharField(blank=True, max_length=100)),
                ('City', models.CharField(blank=True, max_length=100)),
                ('Pincode', models.IntegerField(blank=True)),
                ('State', models.CharField(blank=True, max_length=100)),
                ('Birth_Date', models.DateTimeField(blank=True)),
                ('Blood_Group', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], max_length=2)),
                ('Mobile1', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Mobile2', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('Pending_Balance', models.IntegerField(blank=True)),
                ('Family_Balance', models.IntegerField(blank=True)),
                ('Last_Pay_Date', models.DateTimeField(blank=True, null=True)),
                ('Family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='Patient_List',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.Patient_List'),
        ),
    ]
