# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='Family_Name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
