# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_family_family_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_list',
            name='List',
            field=models.CharField(default='List', max_length=4),
        ),
    ]
