# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_list_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Family_Balance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
