# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20170719_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='City',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Pincode',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='State',
        ),
        migrations.RemoveField(
            model_name='patient_list',
            name='List',
        ),
        migrations.AddField(
            model_name='patient_list',
            name='Name',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='Family_Name',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='First_Name',
            field=models.CharField(max_length=100),
        ),
    ]
