# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20170720_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_list',
            name='Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
