# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_auto_20170720_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Birth_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
