# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20170720_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='First_Name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
    ]
